on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      #install CLI
    - uses: elstudio/action-install-azure-cli@main
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'storagePrefix=bicepfilestorage storageSKU=Standard_LRS'
        failOnStdErr: false
